package com.mobileide.core.logger

/** Compile-time tag constants. Keep sorted. */
object LogTag {
    const val APP             = "App"
    const val AUTOCOMPLETE    = "AutoComplete"
    const val BUILD           = "Build"
    const val CLONE           = "GitClone"
    const val FILE_OPS        = "FileOps"
    const val FILE_TREE       = "FileTree"
    const val FORMATTER       = "CodeFormatter"
    const val GIT             = "GitManager"
    const val INSTALL         = "APKInstall"
    const val LOGGER_RES      = "LoggerRes"
    const val LOGGER_UI       = "LoggerLayoutUI"
    const val MAIN_ACTIVITY   = "MainActivity"
    const val ONBOARDING      = "Onboarding"
    const val PROJECT_MGR     = "ProjectManager"
    const val SCHEME          = "ColorScheme"
    const val SCREEN_DEP      = "Dependencies"
    const val SCREEN_DEV      = "DevSettings"
    const val SCREEN_DIFF     = "DiffViewer"
    const val SCREEN_EDITOR   = "EditorScreen"
    const val SCREEN_GIT      = "GitScreen"
    const val SCREEN_GRADLE   = "GradleTasks"
    const val SCREEN_HOME     = "HomeScreen"
    const val SCREEN_SEARCH   = "ProjectSearch"
    const val SCREEN_SETTINGS = "Settings"
    const val SCREEN_STATS    = "ProjectStats"
    const val SCREEN_TERMINAL = "TerminalScreen"
    const val SCREEN_TODO     = "TodoPanel"
    const val SORA_EDITOR     = "SoraEditor"
    const val STORAGE         = "StoragePermission"
    const val TEXTMATE        = "TextMateSetup"
    const val TERMUX          = "TermuxBridge"
    const val VIEW_MODEL      = "IDEViewModel"
    const val WORKSPACE       = "WorkspaceManager"
}
