/*
 * MobileIDE - A powerful IDE for Android app development.
 * Copyright (C) 2025  scto  <tschmid35@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ktfmt)
    alias(libs.plugins.aboutlibraries)
}

// 1. Update the helper function to return a String directly or handle the provider
fun getGitInfo(vararg args: String): String {
    return try {
        // Execute and get the result immediately during configuration
        val output = providers.exec { commandLine("git", *args) }.standardOutput.asText.get()
        output.trim()
    } catch (e: Exception) {
        "unknown"
    }
}

// 2. Initialize variables
val gitCommitHash = getGitInfo("rev-parse", "--short=8", "HEAD")
val fullGitCommitHash = getGitInfo("rev-parse", "HEAD")
val gitCommitDate = getGitInfo("show", "-s", "--format=%cI", "HEAD")

// ACS_SIGNING_CONFIG_START
val keystorePropertiesFile = file("keystore.properties")
val acsProps =
    if (keystorePropertiesFile.exists()) {
        keystorePropertiesFile
            .readLines()
            .filter { '=' in it }
            .associate { it.substringBefore('=').trim() to it.substringAfter('=').trim() }
    } else emptyMap()

// ACS_SIGNING_CONFIG_END

android {
    namespace = libs.versions.applicationId.get()
    compileSdk = libs.versions.compileSdk.get().toInt()

    defaultConfig {
        applicationId = libs.versions.applicationId.get()
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = libs.versions.versionCode.get().toInt()
        versionName = libs.versions.versionName.get()

        // multiDexEnabled = true

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            //noinspection ChromeOsAbiSupport
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64")
        }
    }

    signingConfigs {
        maybeCreate("release").apply {
            val sf = acsProps["storeFile"]
            val sp = acsProps["storePassword"]
            val ka = acsProps["keyAlias"]
            val kp = acsProps["keyPassword"]
            if (!sf.isNullOrBlank()) storeFile = file(sf)
            if (!sp.isNullOrBlank()) storePassword = sp
            if (!ka.isNullOrBlank()) keyAlias = ka
            if (!kp.isNullOrBlank()) keyPassword = kp
        }
    }
    /*
    signingConfigs {
        create("release") {
            storeFile = file("WebIDE.jks")
            keyAlias = "WebIDE"
            storePassword = "WebIDE"
            keyPassword = "WebIDE"
            enableV1Signing = true
            enableV2Signing = true
        }
    }
    */
    // 3. Now use them directly in buildConfigField without .get()
    buildTypes {
        debug {
            buildConfigField("String", "GIT_COMMIT_HASH", "\"$fullGitCommitHash\"")
            buildConfigField("String", "GIT_SHORT_COMMIT_HASH", "\"$gitCommitHash\"")
            buildConfigField("String", "GIT_COMMIT_DATE", "\"$gitCommitDate\"")

            // applicationIdSuffix = ".debug"
            // versionNameSuffix = "-beta-debug"

            // signingConfig = signingConfigs.getByName("release")
        }
        release {
            buildConfigField("String", "GIT_COMMIT_HASH", "\"$fullGitCommitHash\"")
            buildConfigField("String", "GIT_SHORT_COMMIT_HASH", "\"$gitCommitHash\"")
            buildConfigField("String", "GIT_COMMIT_DATE", "\"$gitCommitDate\"")

            isMinifyEnabled = false
            isShrinkResources = false

            signingConfig = signingConfigs.getByName("release")

            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    // Merged all packaging configurations into a single block
    packaging {
        resources {
            // Exclude conflicting files potentially generated by LSP4J, JGit, and other libraries
            excludes +=
                listOf(
                    "OSGI-INF/l10n/plugin.properties",
                    "META-INF/DEPENDENCIES",
                    "META-INF/LICENSE",
                    "META-INF/LICENSE.txt",
                    "META-INF/license.txt",
                    "META-INF/NOTICE",
                    "META-INF/NOTICE.txt",
                    "META-INF/notice.txt",
                    "META-INF/ASL2.0",
                    "META-INF/*.kotlin_module",
                    "META-INF/INDEX.LIST",
                )
        }

        // Add jniLibs legacy packaging
        jniLibs {
            useLegacyPackaging = true
            keepDebugSymbols.add("**/*.so")
        }
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin { compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) } }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    // Do not compress bin and so files
    androidResources { noCompress += listOf("bin", "proot", "so", "2") }
}

android.applicationVariants.configureEach {
    val variant = this
    outputs.all {
        val output = this as? com.android.build.gradle.internal.api.BaseVariantOutputImpl
        val appName = "MobileIDE"
        val buildType = variant.buildType.name
        val versionName = variant.versionName

        output?.outputFileName = "${appName}-${versionName}-${buildType}.apk"
    }
}

/*
android.applicationVariants.configureEach {
    outputs.configureEach {
        val appName = "MobileIDE"
        val buildType = buildType.name
        val ver = versionName(this as? com.android.build.gradle.internal.api.ApkVariantOutputImpl)?.let {
            it.outputFileName = "${appName}-${ver}-${buildType}.apk"
        }
    }
}
*/

aboutLibraries {
    collect { fetchRemoteLicense = true }
    export {
        prettyPrint = true
        outputFile = file("src/main/res/raw/aboutlibraries.json")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)

        freeCompilerArgs.add("-opt-in=kotlin.RequiresOptIn")
        freeCompilerArgs.add("-Xdeprecation=warn")
    }
}

dependencies {
    implementation(libs.material.kolor)
    implementation(libs.jsoup)
    implementation(libs.coil.compose)
    implementation(libs.coil.svg)

    implementation(libs.accompanist.navigation.animation)
    implementation(libs.compose.icons.simple)
    implementation(libs.compose.icons.font.awesome)

    implementation(libs.aboutlibraries.compose)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.multiplatform.markdown.renderer.m3)
    implementation(libs.multiplatform.markdown.renderer.code)
    implementation(libs.multiplatform.markdown.renderer.coil2)
    implementation(libs.highlights)
    implementation(libs.androidx.compose.animation)
    implementation(libs.androidx.compose.ui)

    // Git dependencies
    // Source: https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit
    implementation(libs.org.eclipse.jgit)
    // Source: https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit.ssh.apache
    implementation(libs.org.eclipse.jgit.ssh.apache)
    //noinspection UseTomlInstead
    implementation("org.slf4j:slf4j-simple:2.0.17")

    // Add terminal dependencies
    implementation(project(":core:main"))

    // LSP support
    implementation(project(":editor-lsp"))
    implementation(libs.lsp4j)
    implementation(libs.androidx.compose.foundation.layout)
    implementation(libs.androidx.compose.ui.ui)

    // TreeSitter language packs
    implementation(libs.tree.sitter)
    implementation(libs.tree.sitter.json)

    // Media3 (Video Player)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.common)

    // Editor
    implementation(project(":editor"))
    implementation(project(":language-treesitter"))
    implementation(libs.language.textmate)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)

    // DataStore dependencies
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.datastore.core)

    implementation(files("libs/xml.jar"))

    implementation(libs.zipalign.java)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.volley)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.ui.text)
    implementation(libs.androidx.compose.runtime)
    implementation(libs.androidx.compose.material3)
    implementation(libs.appcompat)

    // Core Library Desugaring (translates newer Java APIs for older Android versions)
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
