package com.scto.mobile.ide.core.apkbuilder

import android.content.Context
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.util.Properties

data class KeystoreSigningConfig(
    val storeFilePath: String,
    val storePassword: String,
    val keyAlias: String,
    val keyPassword: String,
    val isSaveCredentialsOnDevice: Boolean = true
)

object KeystoreConfigStore {

    private const val PREF_NAME = "MobileIDE_SigningConfigs"

    fun saveSigningConfig(
        context: Context,
        projectPath: String,
        config: KeystoreSigningConfig
    ) {
        if (config.isSaveCredentialsOnDevice) {
            val pref = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
            pref.edit()
                .putString("${projectPath}_storeFile", config.storeFilePath)
                .putString("${projectPath}_storePass", config.storePassword)
                .putString("${projectPath}_alias", config.keyAlias)
                .putString("${projectPath}_keyPass", config.keyPassword)
                .apply()
        }

        // Generate / Update keystore.properties in project root
        writeKeystoreProperties(projectPath, config)
        ensureGitIgnoreEntry(projectPath, "keystore.properties")
    }

    fun loadSigningConfig(
        context: Context,
        projectPath: String
    ): KeystoreSigningConfig? {
        val propsFile = File(projectPath, "keystore.properties")
        if (propsFile.exists()) {
            try {
                val props = Properties()
                FileInputStream(propsFile).use { props.load(it) }
                val storeFile = props.getProperty("storeFile", "")
                val storePass = props.getProperty("storePassword", "")
                val alias = props.getProperty("keyAlias", "")
                val keyPass = props.getProperty("keyPassword", "")
                if (storeFile.isNotEmpty()) {
                    return KeystoreSigningConfig(
                        storeFilePath = storeFile,
                        storePassword = storePass,
                        keyAlias = alias,
                        keyPassword = keyPass
                    )
                }
            } catch (_: Exception) {}
        }

        val pref = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val storeFile = pref.getString("${projectPath}_storeFile", null) ?: return null
        val storePass = pref.getString("${projectPath}_storePass", "") ?: ""
        val alias = pref.getString("${projectPath}_alias", "") ?: ""
        val keyPass = pref.getString("${projectPath}_keyPass", "") ?: ""

        return KeystoreSigningConfig(
            storeFilePath = storeFile,
            storePassword = storePass,
            keyAlias = alias,
            keyPassword = keyPass
        )
    }

    fun writeKeystoreProperties(
        projectPath: String,
        config: KeystoreSigningConfig
    ) {
        val propsFile = File(projectPath, "keystore.properties")
        val props = Properties()
        val relativePath = if (config.storeFilePath.startsWith(projectPath)) {
            config.storeFilePath.removePrefix(projectPath).trimStart('/', '\\')
        } else {
            config.storeFilePath
        }

        props.setProperty("storeFile", relativePath)
        props.setProperty("storePassword", config.storePassword)
        props.setProperty("keyAlias", config.keyAlias)
        props.setProperty("keyPassword", config.keyPassword)

        FileOutputStream(propsFile).use { out ->
            props.store(out, "Auto-generated by MobileIDE Keystore Wizard - DO NOT COMMIT TO GIT")
        }
    }

    fun ensureGitIgnoreEntry(projectPath: String, entry: String) {
        val gitIgnoreFile = File(projectPath, ".gitignore")
        val content = if (gitIgnoreFile.exists()) gitIgnoreFile.readText() else ""
        if (!content.contains(entry)) {
            gitIgnoreFile.appendText("\n$entry\n")
        }
    }
}
